Repository Code-4-Community/jpal-frontend, pull requests merged in 2021-11, with the labels that each got.

#55 Create Survey Body Form Component & Setup State Machine View Controller Logic
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Logo.tsx
  src/components/form/Form.tsx
  src/components/form/InputField.tsx
  src/components/form/MultipleChoiceField.tsx
  src/components/form/NumberInputField.tsx
  src/components/form/types.ts
  src/components/logo.svg
  src/components/survey/SurveyForm.test.tsx
  src/components/survey/SurveyForm.tsx
  src/components/survey/SurveyViewController.tsx
  src/components/survey/defaultQuestions.ts
  src/components/survey/stateMachine.ts
  src/pages/survey/SurveyPage.tsx
  src/theme.ts
Labels: size/l

#54 Survey thank you page done and tested
  src/App.tsx
  src/components/survey/SurveyConfirmation.test.tsx
  src/components/survey/SurveyConfirmation.tsx
Labels: size/s

#53 Added base page, tests, async functionality for admin dashboard
  amplify/README.md
  cypress/integration/admin-dashboard.spec.ts
  src/App.tsx
  src/api/apiClient.ts
  src/api/contracts/getusers.test.pact.js
  src/pages/admin/AdminDashboard.test.tsx
  src/pages/admin/AdminDashboard.tsx
Labels: size/m

#51 Create page for adding an Admin
  cypress/fixtures/example.json
  cypress/integration/add-admin.spec.ts
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiClient.ts
  src/api/contracts/auth.me.test.pact.js
  src/api/contracts/createUser.test.pact.js
  src/components/form/AddAdminForm.tsx
  src/pages/AddAdminPage.tsx
Labels: size/m
