Repository Code-4-Community/jpal-frontend, pull requests merged in 2021-12, with the labels that each got.

#57 Create reviewer confirmation page with tests
  src/App.tsx
  src/components/survey/ReviewerConfirmation.test.tsx
  src/components/survey/ReviewerConfirmation.tsx
  src/pages/survey/ReviewerConfirmationPage.tsx
Labels: size/m

#56 create admin landing page
  cypress/integration/1-getting-started/cognito-login.spec.ts
  src/App.tsx
  src/components/adminLandingPage/SurveyTable.tsx
  src/components/adminLandingPage/SurveyTableRow.tsx
  src/pages/AdminLandingPage.test.tsx
  src/pages/AdminLandingPage.tsx
  src/pages/LandingPage.test.tsx
Labels: size/m

#59 Complete Reviewer Survey Flow
  cypress/integration/add-admin.spec.ts
  cypress/integration/admin-dashboard.spec.ts
  cypress/integration/cognito-login.spec.ts
  cypress/integration/reviewer-survey-flow.spec.ts
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiClient.ts
  src/api/dtos/survey-assignment.dto.ts
  src/components/ErrorAlert.tsx
  src/components/LoadingSpinner.tsx
  src/components/form/MultipleChoiceField.tsx
  src/components/survey/ConfirmAssignments.test.tsx
  src/components/survey/ConfirmAssignments.tsx
  src/components/survey/ConfirmReviewerIdentity.test.tsx
  src/components/survey/ConfirmReviewerIdentity.tsx
  src/components/survey/ConfirmYouth.tsx
  src/components/survey/ControlExplanation.tsx
  src/components/survey/PreviewLetter.tsx
  src/components/survey/SurveyForm.test.tsx
  src/components/survey/SurveyForm.tsx
  src/components/survey/SurveyViewController.tsx
  src/components/survey/ThankYou.test.tsx
  src/components/survey/ThankYou.tsx
  src/components/survey/defaultQuestions.ts
  src/components/survey/generateLetter.ts
  src/components/survey/stateMachine.ts
  src/pages/AddAdminPage.tsx
  src/pages/admin/AdminDashboard.tsx
  src/pages/basicConstants.ts
  src/pages/survey/ConfirmAssignmentsPage.tsx
  src/pages/survey/ReviewerConfirmationPage.tsx
  src/pages/survey/SurveyPage.tsx
Labels: size/xl

#58 Added not found page and removed unused import
  src/App.tsx
  src/components/NotFound.test.tsx
  src/components/NotFound.tsx
  src/components/survey/.SurveyConfirmation.tsx.icloud
  src/pages/NotFoundPage.tsx
Labels: size/s
